[settings]
camera = 2
dwell_ms = 200
format = "GREY"
spread_threshold = 0.4

[[poses]]
name = "FIST"
thumb = false
index = false
middle = false
ring = false
pinky = false

[[poses]]
name = "LLAP"
index = true
middle = true
ring = true
pinky = true
spread_index_middle = "close"
spread_middle_ring = "apart"
spread_ring_pinky = "close"

[[poses]]
name = "OPEN_PALM"
thumb = true
index = true
middle = true
ring = true
pinky = true
spread_thumb_index = "apart"
spread_index_middle = "apart"
spread_middle_ring = "apart"
spread_ring_pinky = "apart"

[[poses]]
name = "FIVE"
thumb = true
index = true
middle = true
ring = true
pinky = true
spread_middle_ring = "close"

[[poses]]
name = "SIGN"
thumb = true
index = true
middle = false
ring = false
pinky = true

[[poses]]
name = "THUMBS_UP"
thumb = true
index = false
middle = false
ring = false
pinky = false

[[poses]]
name = "FOUR"
thumb = false
index = true
middle = true
ring = true
pinky = true
spread_middle_ring = "close"

[[poses]]
name = "THREE"
thumb = true
index = true
middle = true
ring = false
pinky = false

[[poses]]
name = "TWO"
thumb = false
index = true
middle = true
ring = false
pinky = false

[[poses]]
name = "ONE"
thumb = false
index = true
middle = false
ring = false
pinky = false

[[poses]]
name = "L"
thumb = true
index = true
middle = false
ring = false
pinky = false

[[poses]]
name = "OK"
index = false
middle = true
ring = true
pinky = true

[[poses]]
name = "Y"
thumb = true
index = false
middle = false
ring = false
pinky = true

[[bindings]]
name = "tag_cycle"
require = [{hand = "left", pose = "THREE"}]
trigger = { type = "continuous", metric = "pinch_distance", range = [0.1, 0.35], hysteresis = 0.15, hand = "left" }

[[bindings]]
name = "set_volume"
require = [{hand = "left", pose = "L"}]
trigger = { hand = "left", metric = "pinch_distance", range = [0, 0.6], type = "continuous" }

[[bindings]]
name = "stack_cycle"
require = [{hand = "right", pose = "THREE"}]
trigger = { type = "continuous", metric = "pinch_distance", range = [0.1, 0.35], hysteresis = 0.15, hand = "right" }

[[bindings]]
name = "play_pause"
trigger = { hand = "left", step_dwell_ms = 5, steps = ["FIVE", "FOUR"], type = "sequence", window_ms = 1500 }

[[bindings]]
name = "browser_back"
require = [{hand = "either", pose = "TWO"}]
trigger = { direction = "left", hand = "either", min_displacement = 0.1, type = "swipe" }

[[bindings]]
name = "browser_forward"
require = [{hand = "either", pose = "TWO"}]
trigger = { direction = "right", hand = "either", min_displacement = 0.1, type = "swipe" }

[[bindings]]
name = "youtube"
trigger = { dwell_ms = 200, hand = "either", shape = "Y", type = "pose" }
