# ── Rounded Corners ───────────────────────────────────────────────────────
corner-radius = 10;

# ── Blur ──────────────────────────────────────────────────────────────────
blur: {
  method = "dual_kawase";
  strength = 4;
};

# ── Fading ────────────────────────────────────────────────────────────────
fading = true;
fade-delta = 3;
fade-in-step = 0.03;
fade-out-step = 0.01;

# ── Animations ────────────────────────────────────────────────────────────
animations = ({
  triggers = ["close", "open"];
  preset = "disappear";
  scale = 0.7;
  duration = 0.3;
}, {
  triggers = ["hide", "show"];
  preset = "appear";
  scale = 1.0;
  duration = 0.3;
});

# ── Backend ───────────────────────────────────────────────────────────────
backend = "glx";
vsync = true;
use-damage = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
detect-client-leader = true;

# ── Rules ─────────────────────────────────────────────────────────────────
# Last matching rule wins for each property.
rules = (
  # Defaults
  { match = "focused";  opacity = 0.95; },
  { match = "!focused"; opacity = 0.65; },

  # Terminals and editors
  { match = "class_g = 'NeoVim' && focused";    opacity = 0.90; },
  { match = "class_g = 'Alacritty' && focused"; opacity = 0.90; },

  # Rofi
  { match = "class_g = 'Rofi'"; opacity = 0.90; },

  # Always full opacity
  { match = "class_g *= 'Minecraft'";    opacity = 1.0; },
  { match = "name  *= 'YouTube'";        opacity = 1.0; },
  { match = "name  *= 'Video'";          opacity = 1.0; },
  { match = "class_g *= 'HytaleClient'"; opacity = 1.0; },
  { match = "class_g *= 'steam_app'";    opacity = 1.0; },

  # Window types
  { match = "window_type = 'tooltip'";
    opacity = 0.75; fade = true; shadow = true; focus = true; full-shadow = false; },
  { match = "window_type = 'popup_menu'";    opacity = 0.80; },
  { match = "window_type = 'dropdown_menu'"; opacity = 0.80; },
  { match = "window_type = 'dnd'";           shadow = false; },

  # windowDressing - needs to be unmanaged.
  { match = "class_g = 'windowDressing'";
    blur-background = false; shadow = false; fade = false;
    full-shadow = false; transparent-clipping = false; opacity = 1.0; },

  # Dashboard — must be last so nothing overrides it
  { match = "name *= 'Dashboard'";
    opacity = 0.95}
);
