[ids]

3554:fa09:6e440587
3554:fa09:21ebe9de
1b1c:1b3e:1e7da416


[global]

overload_tap_timeout = 200
layer_indicator = 1

[main]

# Keyboard
# CapsLock overloading:
capslock = timeout(grave, 150, toggle(gameMode))


# Homerow Modifiers
a = overloadi(a, timeout(a,150,leftshift), 100)
s = overloadi(s, timeout(s,150,leftcontrol), 100)
d = overloadi(d, timeout(d,150,leftmeta), 100)
f = overloadi(f, timeout(f,200,leftalt), 100)
; = overloadi(;, timeout(;,150,leftshift), 100)
l = overloadi(l, timeout(l,150,leftcontrol), 100)
k = overloadi(k, timeout(k,150,leftmeta), 100)
j = overloadi(j, timeout(j,200,leftalt), 100)

# Other Letter Modifiers
e = overloadi(e, timeout(e,200,esc), 150)
x = overloadi(x, timeout(x,200,macro(leftcontrol+x)), 150)
c = overloadi(c, timeout(c,200,macro(leftcontrol+c)), 150)
v = overloadi(v, timeout(v,200,macro(leftcontrol+v)), 150)

esc = overloadi(esc, timeout(esc, 200, macro(leftmeta+esc)), 150)

# Numbers as F Keys
1 = overloadi(1, timeout(1, 200, f1), 150)
2 = overloadi(2, timeout(2, 200, f2), 150)
3 = overloadi(3, timeout(3, 200, f3), 150)
4 = overloadi(4, timeout(4, 200, f4), 150)
5 = overloadi(5, timeout(5, 200, f5), 150)
6 = overloadi(6, timeout(6, 200, f6), 150)
7 = overloadi(7, timeout(7, 200, f7), 150)
8 = overloadi(8, timeout(8, 200, f8), 150)
9 = overloadi(9, timeout(9, 200, f9), 150)
0 = overloadi(0, timeout(0, 200, f0), 150)
minus = overloadi(minus, timeout(minus, 200, f11), 150)
equal = overloadi(equal, timeout(equal, 200, f12), 150)
pageup = overloadi(pageup, timeout(pageup, 200, home), 150)
pagedown = overloadi(pagedown, timeout(pagedown, 200, end), 150)

[gameMode]
a = a
s = s
d = d
f = f
; = ;
l = l
k = k
j = j
e = e
x = x
c = c
v = v
esc = esc

[meta]
enter = timeout(macro(leftmeta+leftcontrol+1), 100, macro(leftmeta+leftcontrol+leftalt+1))

[meta+control]
enter = macro(leftmeta+leftcontrol+f5)
