[ids]

1532:0244:6da7d5a1
1532:0244:780d3911
1532:0244:7799d7f6

[main]

# Overload pattern:
# Short => macro(leftmeta+leftcontrol+KEY)
# Long => macro(leftmeta+leftcontrol+leftalt+KEY)
# 200ms threshold, 150ms is the short/long boundary


# Modifier key.
leftalt = leftshift

# Main keys.
1 = timeout(macro(M-C-1), 150, M-C-A-1)
2 = timeout(macro(M-C-2), 150, M-C-A-2) 
3 = timeout(macro(M-C-3), 150, M-C-A-3) 
4 = timeout(macro(M-C-4), 150, M-C-A-4) 
5 = timeout(macro(M-C-5), 150, M-C-A-5) 
tab = timeout(macro(M-C-tab), 150, M-C-A-5)
q = timeout(macro(M-C-q), 150, M-C-A-q)
w = timeout(macro(M-C-w), 150, M-C-A-w)
e = timeout(macro(M-C-e), 150, M-C-A-e)
r = timeout(macro(M-C-r), 150, M-C-A-r)
capslock = timeout(macro(M-C-capslock), 150, M-C-A-capslock)
a = timeout(macro(M-C-a), 150, M-C-A-a)
s = timeout(macro(M-C-s), 150, M-C-A-s)
d = timeout(macro(M-C-d), 150, M-C-A-d)
f = timeout(macro(M-C-f), 150, M-C-A-f)
leftshift = timeout(macro(M-C-leftshift ), 150, M-C-A-leftshift)
z = timeout(macro(M-C-z), 150, M-C-A-z)
x = timeout(macro(M-C-x), 150, M-C-A-x)
c = timeout(macro(M-C-c), 150, M-C-A-c)
space = timeout(macro(M-C-space), 150, M-C-A-space)

# Arrow keys.
right = leftalt+leftcontrol+e
left = leftalt+leftcontrol+q

# Scroll wheel
middlemouse = enter
